import csv
import math
from collections import defaultdict
from pathlib import Path

import mlrunner

PROJECT_DIR = Path(__file__).resolve().parent
ROOT_DIR = PROJECT_DIR.parent
RESULTS_FILE = mlrunner.RESULTS_DIR / "baseline_comparison_results.csv"
FIG_FILE = ROOT_DIR / "fig" / "online_baseline_comparison.tex"


def read_rows():
    if not RESULTS_FILE.exists():
        raise FileNotFoundError(f"Missing {RESULTS_FILE}. Run exp/baseline_comparison_runner.py first.")
    with RESULTS_FILE.open("r", newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def mean_std(values):
    mean = sum(values) / len(values)
    if len(values) <= 1:
        return mean, 0.0
    var = sum((value - mean) ** 2 for value in values) / (len(values) - 1)
    return mean, math.sqrt(var)


def aggregate(rows):
    cost = defaultdict(list)
    ratio = defaultdict(list)
    for row in rows:
        K = int(row["K"])
        algorithm = row["algorithm"]
        cost[(algorithm, K)].append(float(row["native_cost"]))
        if row["target_ratio"] != "":
            ratio[(algorithm, K)].append(float(row["target_ratio"]))
    return {key: mean_std(values) for key, values in cost.items()}, {key: mean_std(values) for key, values in ratio.items()}


def coords(stats, algorithm, which):
    points = []
    for alg, K in stats:
        if alg != algorithm:
            continue
        mean, std = stats[(alg, K)]
        if which == "mean":
            y = mean
        elif which == "upper":
            y = mean + std
        elif which == "lower":
            y = max(0.0, mean - std)
        else:
            raise ValueError(which)
        points.append((K, y))
    points.sort()
    return " ".join(f"({x},{y:.8g})" for x, y in points)


def shaded(name, color, mark, mean, upper, lower, legend):
    return rf"""
\addplot[name path={name}upper, draw=none, forget plot] coordinates {{{upper}}};
\addplot[name path={name}lower, draw=none, forget plot] coordinates {{{lower}}};
\addplot[{color}, fill opacity=0.16, draw=none, forget plot]
    fill between[of={name}upper and {name}lower];
\addplot[
    color={color},
    thick,
    mark={mark},
    mark options={{fill=white, draw={color}}}
] coordinates {{{mean}}};
\addlegendentry{{{legend}}}
"""


def simple_plot(stats, name, color, mark, legend):
    return shaded(
        name,
        color,
        mark,
        coords(stats, legend, "mean"),
        coords(stats, legend, "upper"),
        coords(stats, legend, "lower"),
        legend,
    )


def write_figure(rows):
    cost_stats, ratio_stats = aggregate(rows)
    k_values = sorted({int(row["K"]) for row in rows})
    ticks = ",".join(str(k) for k in k_values)

    ucb_cost = (
        simple_plot(cost_stats, "ouc", "myblue", "*", "Our offline UCB")
        + simple_plot(cost_stats, "juc", "myorange", "triangle*", "Jun2018 clipped UCB")
        + simple_plot(cost_stats, "xuc", "mypurple", "square*", "Xu2021 observation-free UCB")
    )
    ts_cost = (
        simple_plot(cost_stats, "ots", "myblue", "*", "Our offline TS")
        + simple_plot(cost_stats, "zts", "myorange", "triangle*", "Zuo2024 clipped TS")
        + simple_plot(cost_stats, "xts", "mypurple", "square*", "Xu2021 observation-free TS")
    )
    ucb_ratio = (
        simple_plot(ratio_stats, "ourucr", "myblue", "*", "Our offline UCB")
        + simple_plot(ratio_stats, "junr", "myorange", "triangle*", "Jun2018 clipped UCB")
    )
    ts_ratio = (
        simple_plot(ratio_stats, "ourtsr", "myblue", "*", "Our offline TS")
        + simple_plot(ratio_stats, "zuor", "myorange", "triangle*", "Zuo2024 clipped TS")
    )

    content = rf"""% Auto-generated by exp/generate_baseline_tikz.py.
% Source file: {RESULTS_FILE}
\begin{{figure*}}[t]
\centering
\subfloat[UCB native attack cost]{{%
\begin{{minipage}}[t]{{0.49\linewidth}}
\centering
\begin{{tikzpicture}}
\begin{{axis}}[
    width=\linewidth,
    height=3.8cm,
    xlabel={{{{\small Number of arms $K$}}}},
    ylabel={{{{\small Native cost}}}},
    ymin=0,
    tick align=outside,
    tick pos=left,
    xtick={{{ticks}}},
    xticklabel style={{font=\scriptsize}},
    yticklabel style={{font=\scriptsize}},
    axis line style={{black}},
    legend pos=north west,
    legend style={{fill opacity=0.55, draw opacity=1, text opacity=1, font=\fontsize{{5}}{{6}}\selectfont, row sep=0pt, inner xsep=2pt, inner ysep=1pt}},
]
{ucb_cost}
\end{{axis}}
\end{{tikzpicture}}
\end{{minipage}}}}
\hfill
\subfloat[Thompson Sampling native attack cost]{{%
\begin{{minipage}}[t]{{0.49\linewidth}}
\centering
\begin{{tikzpicture}}
\begin{{axis}}[
    width=\linewidth,
    height=3.8cm,
    xlabel={{{{\small Number of arms $K$}}}},
    ylabel={{{{\small Native cost}}}},
    ymin=0,
    tick align=outside,
    tick pos=left,
    xtick={{{ticks}}},
    xticklabel style={{font=\scriptsize}},
    yticklabel style={{font=\scriptsize}},
    axis line style={{black}},
    legend pos=north west,
    legend style={{fill opacity=0.55, draw opacity=1, text opacity=1, font=\fontsize{{5}}{{6}}\selectfont, row sep=0pt, inner xsep=2pt, inner ysep=1pt}},
]
{ts_cost}
\end{{axis}}
\end{{tikzpicture}}
\end{{minipage}}}}
\par\vspace{{0.4em}}
\subfloat[UCB target selection ratio]{{%
\begin{{minipage}}[t]{{0.49\linewidth}}
\centering
\begin{{tikzpicture}}
\begin{{axis}}[
    width=\linewidth,
    height=3.8cm,
    xlabel={{{{\small Number of arms $K$}}}},
    ylabel={{{{\small Target ratio}}}},
    ymin=0,
    ymax=1.05,
    tick align=outside,
    tick pos=left,
    xtick={{{ticks}}},
    xticklabel style={{font=\scriptsize}},
    yticklabel style={{font=\scriptsize}},
    axis line style={{black}},
    legend pos=south east,
    legend style={{fill opacity=0.55, draw opacity=1, text opacity=1, font=\fontsize{{5}}{{6}}\selectfont, row sep=0pt, inner xsep=2pt, inner ysep=1pt}},
]
{ucb_ratio}
\end{{axis}}
\end{{tikzpicture}}
\end{{minipage}}}}
\hfill
\subfloat[Thompson Sampling target selection ratio]{{%
\begin{{minipage}}[t]{{0.49\linewidth}}
\centering
\begin{{tikzpicture}}
\begin{{axis}}[
    width=\linewidth,
    height=3.8cm,
    xlabel={{{{\small Number of arms $K$}}}},
    ylabel={{{{\small Target ratio}}}},
    ymin=0,
    ymax=1.05,
    tick align=outside,
    tick pos=left,
    xtick={{{ticks}}},
    xticklabel style={{font=\scriptsize}},
    yticklabel style={{font=\scriptsize}},
    axis line style={{black}},
    legend pos=south east,
    legend style={{fill opacity=0.55, draw opacity=1, text opacity=1, font=\fontsize{{5}}{{6}}\selectfont, row sep=0pt, inner xsep=2pt, inner ysep=1pt}},
]
{ts_ratio}
\end{{axis}}
\end{{tikzpicture}}
\end{{minipage}}}}
\caption{{Comparison with online baselines at $T=200{{,}}000$ over ten repeats. Xu2021 is reported in its native corruption-round cost for the theorem-calibrated phase attack; its sample-equivalent cost is larger by a factor of $K$ and is stored in the CSV. Jun2018 and Zuo2024 are implemented as online non-target lowering attacks, but the realized corrupted reward is clipped below by $\rl$.}}
\label{{fig:online_baseline_comparison}}
\end{{figure*}}
"""
    FIG_FILE.parent.mkdir(parents=True, exist_ok=True)
    FIG_FILE.write_text(content, encoding="utf-8")
    print(f"wrote {FIG_FILE}")


def Main():
    write_figure(read_rows())


if __name__ == "__main__":
    Main()
