import csv
import math
from collections import defaultdict
from pathlib import Path

import mlrunner

PROJECT_DIR = Path(__file__).resolve().parent
ROOT_DIR = PROJECT_DIR
RESULTS_FILE = mlrunner.RESULTS_DIR / "delta_sweep_results.csv"
UCB_FIG_FILE = ROOT_DIR / "fig" / "delta_sweep_ucb.tex"
TS_FIG_FILE = ROOT_DIR / "fig" / "delta_sweep_ts.tex"


def mean_std(values):
    mean = sum(values) / len(values)
    if len(values) < 2:
        return mean, 0.0
    variance = sum((value - mean) ** 2 for value in values) / (len(values) - 1)
    return mean, math.sqrt(variance)


def coords(stats, algorithm, which):
    points = []
    for (name, multiplier), (mean, std) in stats.items():
        if name != algorithm:
            continue
        value = mean if which == "mean" else mean + std if which == "upper" else max(0.0, mean - std)
        points.append((multiplier, value))
    return " ".join(f"({x:g},{y:.8g})" for x, y in sorted(points))


def shaded(stats, algorithm, name, color, mark, legend):
    mean = coords(stats, algorithm, "mean")
    upper = coords(stats, algorithm, "upper")
    lower = coords(stats, algorithm, "lower")
    if not mean:
        return ""
    return rf"""
\addplot[name path={name}upper, draw=none, forget plot] coordinates {{{upper}}};
\addplot[name path={name}lower, draw=none, forget plot] coordinates {{{lower}}};
\addplot[{color}, fill opacity=0.08, draw=none, forget plot]
    fill between[of={name}upper and {name}lower];
\addplot[
    color={color}, thick, mark={mark},
    mark options={{fill=white, draw={color}}}
] coordinates {{{mean}}};
\addlegendentry{{{legend}}}
"""


def figure_content(stats, learner):
    learner_lower = learner.lower()
    plots = (
        shaded(stats, f"{learner} appendix", f"delta{learner_lower}app", "myorange", "o", "Threshold")
        + shaded(stats, f"{learner} direct", f"delta{learner_lower}direct", "myblue", "x", "Direct")
        + shaded(
            stats,
            f"Xu2021 observation-free {learner}",
            f"delta{learner_lower}xu",
            "mypurple",
            "diamond*",
            r"\citet{xu2021observation}",
        )
    )
    return rf"""% Auto-generated by exp/generate_delta_sweep_tikz.py.
\begin{{figure*}}[t]
\centering
\begin{{tikzpicture}}
\begin{{axis}}[
    width=0.72\linewidth,
    height=5.1cm,
    xlabel={{Target gap $\Delta_K/(S_T/T)$}},
    ylabel={{Attack cost}},
    xmin=0, xmax=6,
    ymode=log,
    ymin=700, ymax=200000,
    xtick={{0,0.5,1,1.5,2,3,4,5,6}},
    tick align=outside,
    tick pos=left,
    axis line style={{black}},
    legend columns=3,
    legend style={{
        at={{(0.5,1.03)}}, anchor=south,
        draw=black!35, fill=white,
        font=\scriptsize,
        /tikz/every even column/.append style={{column sep=5pt}}
    }},
]
{plots}
\end{{axis}}
\end{{tikzpicture}}
\caption{{{learner} attack-cost sensitivity to the normalized target gap at $T=200{{,}}000$ and $K=10$; the vertical axis is logarithmic.}}
\label{{fig:delta-sweep-{learner_lower}}}
\end{{figure*}}
"""


def main():
    grouped = defaultdict(list)
    with RESULTS_FILE.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            # As elsewhere in the paper, Xu is not plotted when its native
            # corrupted-round budget reaches or exceeds the horizon.
            if row["status"] != "ok" or row["cost"] == "":
                continue
            grouped[(row["algorithm"], float(row["multiplier"]))].append(float(row["cost"]))
    stats = {key: mean_std(values) for key, values in grouped.items()}

    UCB_FIG_FILE.write_text(figure_content(stats, "UCB"), encoding="utf-8")
    TS_FIG_FILE.write_text(figure_content(stats, "TS"), encoding="utf-8")
    print(f"wrote {UCB_FIG_FILE}")
    print(f"wrote {TS_FIG_FILE}")


if __name__ == "__main__":
    main()
